version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

     - run: docker build -t staeco/pgbouncer:1.9.0-v2 .

     - run: docker push staeco/pgbouncer:1.9.0-v2
